import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import styles from '../styles/Home.module.css'

import Contador from '../components/Contador';
// import Button from '../components/Button'

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home
        </h1>

        <p className={styles.description}>
          a description
        </p>

        {/* <Button></Button> */}
        <Contador />
      </main>

      <footer className={styles.footer}>
        <Link href="/sobre"> Sobre</Link>
      </footer>
    </div>
  )
}

export default Home